### ISSUE TITLE
Can't get the program to execute

### ISSUE THREAD

**Issue by Seany1990** [MPTSakurada/SafeDump#1]
If I run the bat in normal mode, it just immediately closes whenever I drag a folder/vpk file onto it and disappears from task manager
If I run it in administrator, whenever I drag a folder/vpk onto it then it just hangs and doesn't print the confirmation message that should appear according to the source code.

Windows 10 anniversary

**Comment by MPTSakurada** [comment]
Try running it from the command prompt and seeing what is output, posting it here. Also make sure the DotNetZip.dll is in the same folder as the exe.

**Comment by boltexcuse** [comment]
Better way is drag & drop folder(with vpk or zip inside) into SafeDump.exe

Works for me

**Comment by Seany1990** [comment]
Sorry I'm an idiot who can't read, program works fine when I follow the instructions correctly.
